name: tailscale-ssh-machine

on:
  workflow_call:
    inputs:
      runs-on:
        description: "Target runner"
        required: true
        type: string
        default: "ubuntu-latest"
      hostname:
        description: "Hostname for machine"
        required: false
        type: string
        default: "rdesktop"

jobs:
  machine-test-runner:
    runs-on: ${{ inputs.runs-on }}
    
    steps:
      - name: Enable linger and start user session (workaround)
        uses: gbraad-actions/blacksmith-user-session@main

      - name: WarpBuild Unprivileged userns (workaround)
        uses: gbraad-actions/warpbuild-unprivileged-userns@main

      - name: Remove unwanted stuff
        uses: gbraad-devenv/remove-unwanted@v1

      - name: Tailscale
        uses: gbraad-actions/tailscale-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh --accept-dns=false --operator=runner
          hostname: ${{ inputs.hostname }}

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Download server binary
        run: |
           python -m pip install --upgrade pip
           pip install requests
           python ./scripts/download.py "https://www.minecraft.net/en-us/download/server/bedrock"

      - name: Run Machinefile commands
        uses: gbraad-actions/machinefile-executor-action@v1
        with:
          containerfile: 'Containerfile'
          context: '.'

      - name: Run server
        run: |
          sudo systemctl daemon-reload
          sudo systemctl start minecraft-server
          sudo systemctl status minecraft-server

      - name: Usage message
        run: |
          IP=`tailscale ip -4`
          echo "Use the following command to connect \`tailscale ssh runner@${IP}\`"

      - name: Hang around
        run: |
          sleep 18000

      - name: Message user; 1 hour
        run: |
          sudo wall "about 1 hour remaining"
          sleep 1800

      - name: Message user; 20 minutes
        run: |
          sudo wall "20 minutes remaining"
          sleep 1200

      - name: Stop and move worlds folder
        if: ${{ always() }}
        run: |
          sudo systemctl stop minecraft-server
          sudo mv ~minecraft/worlds ${{ github.workspace }}/worlds

      - name: Upload Artifact - Worlds
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: worlds
          path: ${{ github.workspace }}/worlds
          retention-days: 1
          include-hidden-files: true
