name: tailscale-ssh-machine

on:
  workflow_dispatch:

jobs:
  ssh-machine:
    name: Tailscale SSH Machine - GitHub
    uses: ./.github/workflows/reusable-tailscale-machine.yml
    with:
      runs-on: "ubuntu-latest"
      hostname: "gaming-minecraft-server"
    secrets: inherit
